# -*- coding: utf-8 -*-


CREDIT_CARD = {
    u"payment_by_credit_card": u"img src='/beloil-map/geticon.jpg?t=p&id=3'",
}
ADDITIONAL = {
        u"carwash" : u"img src='/beloil-map/geticon.jpg?t=s&id=10'",
        u"carwash" : u"img src='/beloil-map/geticon.jpg?t=s&id=9'",
        u"auto_cleaner" : u"img src='/beloil-map/geticon.jpg?t=s&id=12'",
        u"tyre" : u"img src='/beloil-map/geticon.jpg?t=s&id=11'",
        u"tire" : u"img src='/beloil-map/geticon.jpg?t=s&id=8'",
        u"str" : u"img src='/beloil-map/geticon.jpg?t=s&id=7'",
        u"water_glass_washer" : u"img src='/beloil-map/geticon.jpg?t=s&id=26'",
}

FUEL_CARDS = {
        u"e100":u"img src='/beloil-map/geticon.jpg?t=p&id=7'",
        u"petrolplus":u"img src='/beloil-map/geticon.jpg?t=p&id=8'",
        u"aris":u"img src='/beloil-map/geticon.jpg?t=p&id=28'",
        u"inforkom":u"img src='/beloil-map/geticon.jpg?t=p&id=68'",

}
SERVICES = {
    # u"wifi" : u"img src='/beloil-map/geticon.jpg?t=s&id=190'",
    u"toilet" : u"img src='/beloil-map/geticon.jpg?t=s&id=14'",
    u"shop" : u"img src='/beloil-map/geticon.jpg?t=s&id=1'",
    u"cafe" : u"img src='/beloil-map/geticon.jpg?t=s&id=2'",
    u"cafe" : u"img src='/beloil-map/geticon.jpg?t=s&id=3'",
    # u"beverages_implementation" : u"img src='/beloil-map/geticon.jpg?t=s&id=5'",
    # u"hot_beverages_implementation" : u"img src='/beloil-map/geticon.jpg?t=s&id=24'",
    # u"bus_implementation" : u"img src='/beloil-map/geticon.jpg?t=s&id=6'",
    # u"terminal_cards" : u"img src='/beloil-map/geticon.jpg?t=s&id=30'",
    # u"terminal_cards_nal" : u"img src='/beloil-map/geticon.jpg?t=s&id=31'",
    # u"shower" : u"img src='/beloil-map/geticon.jpg?t=s&id=16'",
    # u"hotel" : u"img src='/beloil-map/geticon.jpg?t=s&id=18'",
    # u"parking" : u"img src='/beloil-map/geticon.jpg?t=s&id=13'",
    # u"payphone" : u"img src='/beloil-map/geticon.jpg?t=s&id=20'",
    # u"paid_parking" : u"img src='/beloil-map/geticon.jpg?t=s&id=27'",
    # u"fastfood" : u"img src='/beloil-map/geticon.jpg?t=s&id=130'",
    # u"payment_ways" : u"img src='/beloil-map/geticon.jpg?t=s&id=150'",
    # u"gift_certificate" : u"img src='/beloil-map/geticon.jpg?t=s&id=251'",
    # u"charging_car" : u"img src='/beloil-map/geticon.jpg?t=s&id=210'",
    # u"adblue" : u"img src='/beloil-map/geticon.jpg?t=s&id=90'",
    # u"trailer_rentails" : u"img src='/beloil-map/geticon.jpg?t=s&id=170'",
    # u"camping" : u"img src='/beloil-map/geticon.jpg?t=s&id=230'",
    # u"pto" : u"img src='/beloil-map/geticon.jpg?t=s&id=28'",
    # u"bed" : u"img src='/beloil-map/geticon.jpg?t=s&id=29'",
    # u"trade_trading_floor" : u"img src='/beloil-map/geticon.jpg?t=s&id=22'",
    # u"trade_operator" : u"img src='/beloil-map/geticon.jpg?t=s&id=4'",
    # u"insurance_services" : u"img src='/beloil-map/geticon.jpg?t=s&id=17'",
    # u"bankomat" : u"img src='/beloil-map/geticon.jpg?t=s&id=19'",
    # u"toilet_for_invalid" : u"img src='/beloil-map/geticon.jpg?t=s&id=25'",
    # u"kerosene_packed" : u"img src='/beloil-map/geticon.jpg?t=s&id=110'",
    # u"osobino_ready" : u"img src='/beloil-map/geticon.jpg?t=s&id=71'",
    # u"osobino_chilled" : u"img src='/beloil-map/geticon.jpg?t=s&id=73'",
    # u"osobino_frozen" : u"img src='/beloil-map/geticon.jpg?t=s&id=72'",
    # u"service_refueling_tanker_car" : u"img src='/beloil-map/geticon.jpg?t=s&id=21'",
}

FUELS = {
    u"a_95" : u"img src='/beloil-map/geticon.jpg?t=f&id=1",
    u"a_92" : u"img src='/beloil-map/geticon.jpg?t=f&id=89'",
    u"a_98" : u"img src='/beloil-map/geticon.jpg?t=f&id=128'",
    # u"gaz" : u"img src='/beloil-map/geticon.jpg?t=f&id=6'",
    u"kerosene" : u"img src='/beloil-map/geticon.jpg?t=f&id=5'",
    u"gm" : u"img src='/beloil-map/geticon.jpg?t=f&id=68'",
    # u"dt2" : u"img src='img src='/beloil-map/geticon.jpg?t=f&id=8'",
}

BY_CITIES = {
    u"Минская область": [
        u"Логойский",
        u"Бокшицкий",
        u"Березино",
        u"Борисов",
        u"Вилейка",
        u"Вишневка",
        u"Воложин",
        u"Дзержинск",
        u"Дещенский",
        u"Красное",
        u"Ивенец",
        u"Клецк",
        u"Копыль",
        u"Крупки",
        u"Логойск",
        u"Любань",
        u"Заславль",
        u"Молодечно",
        u"Малявка",
        u"Мядель",
        u"Несвиж",
        u"Марьина Горка",
        u"Слуцк",
        u"Смолевичи",
        u"Смиловичи",
        u"Солигорск",
        u"Старые Дороги",
        u"Столбцы",
        u"Фаниполь",
        u"Узда",
        u"Червень",
        u"Жодино",
        u"Озерцы",
        u"Поречье",
        u"Заболоть",
        u"Новоселки",
        u"Хозянинки",
        u"Озерцо",
        u"Хотлянский",
        u"Папернянский",
        u"Дещенский",
        u"Щомыслицкий",
        u"Новодворский",
        u"Колодищанский",
        u"Фанипольский",
        u"Горанский",
        u"Плещеницкий",
        u"Гайненский",
        u"Сеницкий",
        u"Попернянский",
        u"Боровлянский",
        u"Колядичи",
        u"Сокол",
    ],
    u"Брестская область": [
        u"Барановичи",
        u"Брест",
        u"Береза",
        u"Ганцевичи",
        u"Видомля",
        u"Высокое",
        u"Дрогичин",
        u"Дивин",
        u"Жабинка",
        u"Иваново",
        u"Ивацевичи",
        u"Каменец",
        u"Каменюки",
        u"Кобрин",
        u"Лунинец",
        u"Ляховичы",
        u"Малорита",
        u"Пинск",
        u"Пружаны",
        u"Столин",
        u"Невель",
        u"Сосновка",
        u"Бытень",
        u"Углы",
        u"Новоселки",
        u"Березовичи",
        u"Поречье",
        u"Посеничи",
        u"Томашовка",
        u"Мотоль",
    ],
    u"Витебская область": [
        u"Браслав",
        u"Бешенковичи",
        u"Бегомль",
        u"Бочейково",
        u"Верхнедвинск",
        u"Ветрино",
        u"Воропаево",
        u"Видзы",
        u"Глубокое",
        u"Городок",
        u"Докшицы",
        u"Дубровно",
        u"Друя",
        u"Езерище",
        u"Красносельцы",
        u"Фролковичи",
        u"Лепель",
        u"Лиозно",
        u"Лукомль",
        u"Лынтупы",
        u"Миоры",
        u"Новополоцк",
        u"Орша",
        u"Освея",
        u"Остевичи",
        u"Полоцк",
        u"Подсвилье",
        u"Поставы",
        u"Прозороки",
        u"Россоны",
        u"Сенно",
        u"Сураж",
        u"Толочин",
        u"Тросно",
        u"Чернещино",
        u"Ушачи",
        u"Чашники",
        u"Шарковщина",
        u"Шумилино",
        u"Вороны",
        u"Озеры",
        u"Сосновка",
        u"Волколата",
        u"Крулевщина",
        u"Азино",
        u"Новоселки",
        u"Сорочино",
        u"Муравничи",
        u"Бегомльский",
        u"Хомяково",
    ],
    u"Гомельская область": [
        u"Брагин",
        u"Буда-Кошелево",
        u"Урицкое",
        u"Ветка",
        u"Добруш",
        u"Ельск",
        u"Житковичи",
        u"Жлобин",
        u"Калинковичи",
        u"Корма",
        u"Копаткевичи",
        u"Лельчицы",
        u"Лоев",
        u"Мозырь",
        u"Наровля",
        u"Октябрьский",
        u"Петриков",
        u"Речица",
        u"Рогачев",
        u"Светлогорск",
        u"Чечерск",
        u"Хойники",
        u"Поречье",
        u"Добрынский",
        u"Защебье",
        u"Довск",
        u"Лясковичи",
        u"Новая Гута",
        u"Паричский Поселковый Совет",
        u"Губичский",
        u"Жмуровский",
        u"Козенский",
        u"Ереминский",
        u"Тереховский поселковый Совет",
    ],
    u"Гродненская область": [
        u"Бол.Берестовица",
        u"Березовка",
        u"Будёновка",
        u"Василишки",
        u"Волковыск",
        u"Вороново",
        u"Ворона",
        u"Желудок",
        u"Дятлово",
        u"Зельва",
        u"Ивье",
        u"Красносельский",
        u"Каменный лог",
        u"Кореличи",
        u"Козловщина",
        u"Лида",
        u"Мосты",
        u"Муравщизна",
        u"Новогрудок",
        u"Новая Стража",
        u"Новоельня",
        u"Ошмяны",
        u"Островец",
        u"Островенский",
        u"Острино",
        u"Островля",
        u"Порозово",
        u"Скидель",
        u"Радунь",
        u"Свислочь",
        u"Слоним",
        u"Сморгонь",
        u"Чемеры",
        u"Щучин",
        u"Заболоть",
        u"Озеры",
        u"Михалишки",
        u"Новоселки",
        u"Поречье",
        u"Сосновка",
        u"Моринский",
        u"Пограничный",
        u"Олекшицы",
    ],
    u"Могилевская область": [
        u"Белыничи",
        u"Бобруйск",
        u"Бол. Бортники",
        u"Быхов",
        u"Горки",
        u"Глуск",
        u"Дрибин",
        u"Елизово",
        u"Кировск",
        u"Климовичи",
        u"Кличев",
        u"Костюковичи",
        u"Краснополье",
        u"Кричев",
        u"Круглое",
        u"Мстиславль",
        u"Осиповичи",
        u"Славгород",
        u"Хотимск",
        u"Чаусы",
        u"Чериков",
        u"Шклов",
        u"Новоселки",
        u"Сычково",
        u"Чечевичи",
        u"Белица",
        u"Звенчатка",
        u"Ходосы",
        u"Ректа",
        u"Достижение",
        u"Коммунаровский",
        u"Коптевский",
    ]
}

BY_TYL_CODES = [unicode(x) for x in (
    2232,
    1643,
    1715,
    1511,
    2251,
    1777,
    2344,
    162,
    2336,
    2231,
    2330,
    1771,
    1512,
    1772,
    1594,
    1646,
    2230,
    232,
    2233,
    1522,
    1716,
    2333,
    1644,
    1563,
    2354,
    1641,
    2353,
    2334,
    1775,
    1564,
    1652,
    1645,
    1595,
    2345,
    1631,
    2237,
    1793,
    2244,
    2248,
    2236,
    1642,
    1719,
    1596,
    2337,
    2245,
    2238,
    2241,
    2234,
    1796,
    2356,
    1561,
    1774,
    2347,
    1647,
    1794,
    1633,
    1651,
    1713,
    2222,
    222,
    2351,
    1773,
    1515,
    2240,
    1797,
    2355,
    1797,
    1770,
    1597,
    2357,
    2235,
    1591,
    1593,
    2350,
    1653,
    1632,
    1713,
    2340,
    2339,
    2342,
    1513,
    2246,
    1562,
    1795,
    1776,
    1592,
    1710,
    1792,
    1717,
    1655,
    1718,
    2346,
    2247,
    2242,
    1714,
    2243,
    1732,
    2332,
    2239,
    1514,
    2131,
    2130,
    2132,
    2133,
    2135,
    2136,
    225,
    17,
    25,
    163,
    212,
    214,
    215,
    216,
    152,
    2139,
    154,
    2138,
    236,
    29,
    44,

)]
